const Sequelize = require("sequelize");

module.exports.recommendations ={
    id:{
        type:Sequelize.UUID,
        defaultValue : Sequelize.UUIDV4,
        allowNull:false,
        unique : true,
        primaryKey:true,
    },
    priority:{
        type:Sequelize.STRING,
        allowNull:false,
    },
    po_number:{
        type:Sequelize.STRING,
        allowNull:false,
    },
    demand_value:{
        type:Sequelize.STRING,
        allowNull:false,
    },
    demand_type:{
        type:Sequelize.STRING,
        allowNull:false,
    },
    time_frame:{
        type:Sequelize.STRING,
        allowNull:false,
    },
    available_inventory_value:{
        type:Sequelize.STRING,
        allowNull:false,
    },
    po_quantity_value:{
        type:Sequelize.STRING,
        allowNull:false,
    },
    active:{
        type:Sequelize.BOOLEAN,
        allowNull:false,
    },
    description:{
        type:Sequelize.STRING,
        allowNull:false
    },
    material_code:{
        type:Sequelize.STRING,
        allowNull:true
    },
    plant_code:{
        type:Sequelize.STRING,
        allowNull:true
    },
    firm_zone_time:{
        type:Sequelize.DATE,
        allowNull:true
    },
    total_adjustment:{
        type:Sequelize.STRING,
        allowNull:true
    },
    order_type:{
        type:Sequelize.STRING,
        allowNull:true
    },
    volume:{
        type:Sequelize.STRING,
        allowNull:true
    },
    supplier:{
        type:Sequelize.STRING,
        allowNull:true
    },
    lead_time:{
        type:Sequelize.STRING,
        allowNull:true
    },
    status:{
        type:Sequelize.STRING,
        allowNull:false
    },
    detail_desc:{
        type:Sequelize.STRING,
        allowNull:false
    },
    change_in_demand:{
        type:Sequelize.STRING,
        allowNull:true
    },
    source_location:{
        type:Sequelize.STRING,
        allowNull:false
    },
    open_orders:{
        type:Sequelize.STRING,
        allowNull:true
    },
    in_transit_orders:{
        type:Sequelize.STRING,
        allowNull:true
    },
    user_desc:{
        type:Sequelize.STRING,
        allowNull:true
    },
    recommendation_action:{
        type:Sequelize.STRING,
        allowNull:true
    },
    use_case_id:{
        type:Sequelize.STRING,
        allowNull:false
    },
    due_date:{
        type:Sequelize.DATE,
        allowNull:false
    }
}
